apiVersion: apps/v1
kind: Deployment
metadata:
  name: details
  namespace: poke-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: details
  template:
    metadata:
      labels:
        app: details
    spec:
      containers:
        - name: details
          image: REPLACE_WITH_DOCKERFILE_DEV_PATH
          args:
            - "src.services.details:main"
          env:
            - name: ENTRYPOINT_MODULE
              value: "src.services.details:main"
---
apiVersion: v1
kind: Service
metadata:
  name: details
  namespace: poke-namespace
spec:
  selector:
    app: details
  ports:
    - protocol: TCP
      port: 80 # Replace with the appropriate port
      targetPort: 80 # Replace with the appropriate port
  type: ClusterIP
