apiVersion: apps/v1
kind: Deployment
metadata:
  name: images
  namespace: poke-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: images
  template:
    metadata:
      labels:
        app: images
    spec:
      containers:
        - name: images
          image: REPLACE_WITH_DOCKERFILE_DEV_PATH
          args:
            - "src.images.market:main"
          env:
            - name: ENTRYPOINT_MODULE
              value: "src.images.market:main"
---
apiVersion: v1
kind: Service
metadata:
  name: images
  namespace: poke-namespace
spec:
  selector:
    app: images
  ports:
    - protocol: TCP
      port: 80 # Replace with the appropriate port
      targetPort: 80 # Replace with the appropriate port
  type: ClusterIP
